# Generated by Django 5.2.6 on 2025-10-01 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='title',
            new_name='Title',
        ),
    ]
