# Generated by Django 5.2.6 on 2025-10-01 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_rename_title_todos_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='Title',
        ),
        migrations.AlterField(
            model_name='todos',
            name='created_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2025, 10, 1, 6, 24, 44, 787693, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='todos',
            name='deleted_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='todos',
            name='updated_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AddField(
            model_name='todos',
            name='title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
