# Generated by Django 5.2.6 on 2025-10-01 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_remove_todos_title_alter_todos_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='created_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2025, 10, 1, 6, 28, 45, 114907, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='todos',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='todos',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
