# Generated by Django 5.2.6 on 2025-10-01 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_alter_todos_created_at_alter_todos_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='created_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2025, 10, 1, 7, 56, 20, 516839, tzinfo=datetime.timezone.utc)),
        ),
    ]
