# Generated by Django 5.2.6 on 2025-10-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_alter_todos_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
