# Generated by Django 5.2.6 on 2025-10-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_alter_todos_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
