# Generated by Django 5.2.6 on 2025-10-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0009_alter_todos_created_at_alter_todos_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='deleted_at',
            field=models.DateTimeField(),
        ),
    ]
