# Generated by Django 5.2.6 on 2025-10-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0010_alter_todos_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
    ]
