# Generated by Django 5.2.6 on 2025-10-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0012_alter_todos_deleted_at_alter_todos_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='marked',
            field=models.BooleanField(default=False),
        ),
    ]
